% Initialize the options
options = psooptimset('DemoMode','fast', ...
    'PlotFcns', {@psoplotswarmsurf, @psoplotbestf, @psoplotvelocity}, ...
    'PopInitRange', [-32; 32], ...
    'InertiaWeight', [0.7968; 0.4], ...  
    'SocialAttraction', 1.49, ...
    'CognitiveAttraction', 1.49);

options = psooptimset(options, 'Generations', 500);

% Run PSO optimization
[x, fval] = pso(@ackleysfcn, 20, [], [], [], [], [], [], [], options);

% Save the figure
saveas(gcf, 'figures/min/pso_best_fitness_weight_decay.png');  